# ruff: noqa: E501
DEFAULT_HEADERS = [
    {
        "header": {
            "sec-ch-ua": '"Chromium";v="116", "Not)A;Brand";v="24", "Google Chrome";v="116"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"macOS"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.258,
    },
    {
        "header": {
            "sec-ch-ua": '"Chromium";v="104", " Not A;Brand";v="99", "Google Chrome";v="104"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"Windows"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.1691,
    },
    {
        "header": {
            "sec-ch-ua": '"Chromium";v="104", " Not A;Brand";v="99", "Google Chrome";v="104"',
            "sec-ch-ua-mobile": "?0",
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0829,
    },
    {
        "header": {
            "sec-ch-ua-platform": '"Windows"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0818,
    },
    {
        "header": {
            "sec-ch-ua": '"Chromium";v="104", " Not A;Brand";v="99", "Google Chrome";v="104"',
            "sec-ch-ua-mobile": "?1",
            "sec-ch-ua-platform": '"Android"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (Linux; Android 13; SM-A135F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Mobile Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0501,
    },
    {
        "header": {
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0433,
    },
    {
        "header": {
            "sec-ch-ua": '"Chromium";v="124", "Microsoft Edge";v="124", "Not-A.Brand";v="99"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"Windows"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br, zstd",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0394,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 17_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4.1 Mobile/15E148 Safari/604.1",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0323,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4.1 Safari/605.1.15",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0277,
    },
    {
        "header": {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
            "Accept-Language": "en-US;q=1.0",
            "Accept-Encoding": "gzip, deflate, br",
            "Upgrade-Insecure-Requests": "1",
            "Sec-Fetch-Dest": "navigate",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-User": "document",
            "Te": "trailers",
        },
        "probability": 0.0242,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/120.0.6099.101 Mobile/15E148 Safari/604.1",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
            "Sec-Fetch-Dest": "navigate",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-Site": "?1",
        },
        "probability": 0.016,
    },
    {
        "header": {
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:125.0) Gecko/20100101 Firefox/125.0",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
            "Accept-Language": "en-US;q=1.0",
            "Accept-Encoding": "gzip, deflate, br",
            "Upgrade-Insecure-Requests": "1",
            "Sec-Fetch-Dest": "navigate",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-User": "document",
            "Te": "trailers",
        },
        "probability": 0.0117,
    },
    {
        "header": {
            "sec-ch-ua": '"Chromium";v="104", " Not A;Brand";v="99", "Google Chrome";v="104"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"Linux"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br, zstd",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0089,
    },
    {
        "header": {
            "sec-ch-ua": '"Chromium";v="104", " Not A;Brand";v="99", "Google Chrome";v="104"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"Linux"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0088,
    },
    {
        "header": {
            "sec-ch-ua": '"Chromium";v="104", " Not A;Brand";v="99", "Google Chrome";v="104"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"Linux"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0083,
    },
    {
        "header": {
            "sec-ch-ua": '"Chromium";v="104", " Not A;Brand";v="99", "Google Chrome";v="104"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"Linux"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br, zstd",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0083,
    },
    {
        "header": {
            "sec-ch-ua": "",
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"macOS"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0073,
    },
    {
        "header": {
            "sec-ch-ua": '"Chromium";v="116", "Not)A;Brand";v="24", "Google Chrome";v="116"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '""',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0071,
    },
    {
        "header": {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
            "Accept-Language": "en-US;q=1.0",
            "Accept-Encoding": "gzip, deflate, br, zstd",
            "Upgrade-Insecure-Requests": "1",
            "Sec-Fetch-Dest": "navigate",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-User": "document",
            "Te": "trailers",
        },
        "probability": 0.0063,
    },
    {
        "header": {
            "sec-ch-ua": '"Chromium";v="116", "Not)A;Brand";v="24", "Google Chrome";v="116"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"macOS"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.005,
    },
    {
        "header": {
            "sec-ch-ua": '"Not_A Brand";v="99", "Google Chrome";v="109", "Chromium";v="109"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"Windows"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.005,
    },
    {
        "header": {
            "sec-ch-ua": '"Chromium";v="124", "Microsoft Edge";v="124", "Not-A.Brand";v="99"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"macOS"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br, zstd",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0044,
    },
    {
        "header": {
            "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
            "Accept-Language": "en-US;q=1.0",
            "Accept-Encoding": "gzip, deflate, br",
            "Upgrade-Insecure-Requests": "1",
            "Sec-Fetch-Dest": "navigate",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-User": "document",
            "Te": "trailers",
        },
        "probability": 0.0042,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3.1 Safari/605.1.15",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.003,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0026,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0023,
    },
    {
        "header": {
            "sec-ch-ua": '"Chromium";v="118", "Google Chrome";v="118", "Not=A?Brand";v="99"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"Linux"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.002,
    },
    {
        "header": {
            "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
            "Accept-Language": "en-US;q=1.0",
            "Accept-Encoding": "gzip, deflate, br",
            "Upgrade-Insecure-Requests": "1",
            "Sec-Fetch-Dest": "navigate",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-User": "document",
            "Te": "trailers",
        },
        "probability": 0.002,
    },
    {
        "header": {
            "sec-ch-ua": '"Microsoft Edge";v="125", "Chromium";v="125", "Not.A/Brand";v="24"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"Windows"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br, zstd",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.002,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.002,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0019,
    },
    {
        "header": {
            "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="96"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"Linux"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0018,
    },
    {
        "header": {
            "sec-ch-ua": '"Microsoft Edge";v="123", "Not:A-Brand";v="8", "Chromium";v="123"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"Windows"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br, zstd",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0017,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0016,
    },
    {
        "header": {
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:126.0) Gecko/20100101 Firefox/126.0",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
            "Accept-Language": "en-US;q=1.0",
            "Accept-Encoding": "gzip, deflate, br, zstd",
            "Upgrade-Insecure-Requests": "1",
            "Sec-Fetch-Dest": "navigate",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-User": "document",
            "Te": "trailers",
        },
        "probability": 0.0016,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Safari/605.1.15",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0015,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 17_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3.1 Mobile/15E148 Safari/604.1",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0013,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0013,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 17_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) GSA/315.0.630091404 Mobile/15E148 Safari/604.1",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0012,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Safari/605.1.15",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0012,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3 Safari/605.1.15",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0012,
    },
    {
        "header": {
            "sec-ch-ua": '"Chromium";v="124", "Microsoft Edge";v="124", "Not-A.Brand";v="99"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"Windows"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.001,
    },
    {
        "header": {
            "User-Agent": "Mozilla/5.0 (Android 14; Mobile; rv:125.0) Gecko/125.0 Firefox/125.0",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
            "Accept-Language": "en-US;q=1.0",
            "Accept-Encoding": "gzip, deflate, br",
            "Upgrade-Insecure-Requests": "1",
            "Sec-Fetch-Dest": "navigate",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-User": "document",
            "Te": "trailers",
        },
        "probability": 0.001,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1.2 Safari/605.1.15",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.001,
    },
    {
        "header": {
            "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
            "Accept-Language": "en-US;q=1.0",
            "Accept-Encoding": "gzip, deflate, br",
            "Upgrade-Insecure-Requests": "1",
            "Sec-Fetch-Dest": "navigate",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-User": "document",
            "Te": "trailers",
        },
        "probability": 0.0009,
    },
    {
        "header": {
            "sec-ch-ua": '"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"macOS"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0009,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 15_8_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.6 Mobile/15E148 Safari/604.1",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0008,
    },
    {
        "header": {
            "sec-ch-ua": '"Not?A_Brand";v="8", "Chromium";v="108", "Google Chrome";v="108"',
            "sec-ch-ua-mobile": "?1",
            "sec-ch-ua-platform": '"Android"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (Linux; Android 13; XQ-CT54) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Mobile Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0008,
    },
    {
        "header": {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
            "Accept-Language": "en-US;q=1.0",
            "Accept-Encoding": "gzip, deflate, br",
            "Upgrade-Insecure-Requests": "1",
            "Sec-Fetch-Dest": "navigate",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-User": "document",
            "Te": "trailers",
        },
        "probability": 0.0008,
    },
    {
        "header": {
            "sec-ch-ua": '"Google Chrome";v="117", "Not;A=Brand";v="8", "Chromium";v="117"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"Linux"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0008,
    },
    {
        "header": {
            "sec-ch-ua": '"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"Windows"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br, zstd",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0007,
    },
    {
        "header": {
            "sec-ch-ua": '"Chromium";v="118", "Google Chrome";v="118", "Not=A?Brand";v="99"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"macOS"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0007,
    },
    {
        "header": {
            "sec-ch-ua": '"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"Linux"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br, zstd",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0007,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0007,
    },
    {
        "header": {
            "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
            "Accept-Language": "en-US;q=1.0",
            "Accept-Encoding": "gzip, deflate, br",
            "Upgrade-Insecure-Requests": "1",
            "Sec-Fetch-Dest": "navigate",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-User": "document",
            "Te": "trailers",
        },
        "probability": 0.0007,
    },
    {
        "header": {
            "sec-ch-ua": '"Google Chrome";v="119", "Chromium";v="119", "Not?A_Brand";v="24"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"Linux"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0007,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Safari/605.1.15",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0007,
    },
    {
        "header": {
            "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
            "Accept-Language": "en-US;q=1.0",
            "Accept-Encoding": "gzip, deflate, br",
            "Upgrade-Insecure-Requests": "1",
            "Sec-Fetch-Dest": "navigate",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-User": "document",
            "Te": "trailers",
        },
        "probability": 0.0007,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 16_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0006,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1 SeoSiteCheckup (https://seositecheckup.com)",
            "Accept-Encoding": "gzip, deflate, br, zstd",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0006,
    },
    {
        "header": {
            "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="96"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"Linux"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br, zstd",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0006,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 16_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Mobile/15E148 Safari/604.1",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0006,
    },
    {
        "header": {
            "sec-ch-ua": '"Not.A/Brand";v="8", "Chromium";v="114", "Google Chrome";v="114"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"Linux"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br, zstd",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0006,
    },
    {
        "header": {
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
            "Accept-Language": "en-US;q=1.0",
            "Accept-Encoding": "gzip, deflate, br",
            "Upgrade-Insecure-Requests": "1",
            "Sec-Fetch-Dest": "navigate",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-User": "document",
            "Te": "trailers",
        },
        "probability": 0.0006,
    },
    {
        "header": {
            "sec-ch-ua": '"Chromium";v="112", "Google Chrome";v="112", "Not:A-Brand";v="99"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"Linux"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0005,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 16_7_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0005,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6.1 Safari/605.1.15",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0005,
    },
    {
        "header": {
            "sec-ch-ua": '"Chromium";v="116", "Not)A;Brand";v="24", "Google Chrome";v="116"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"Linux"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0005,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (iPad; CPU OS 17_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0005,
    },
    {
        "header": {
            "sec-ch-ua": '"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"',
            "sec-ch-ua-mobile": "?1",
            "sec-ch-ua-platform": '"Android"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br, zstd",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0005,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0005,
    },
    {
        "header": {
            "sec-ch-ua": '"Chromium";v="124", "Microsoft Edge";v="124", "Not-A.Brand";v="99"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"Linux"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br, zstd",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0005,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0005,
    },
    {
        "header": {
            "sec-ch-ua": '"Not.A/Brand";v="8", "Chromium";v="114", "Google Chrome";v="114"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"Linux"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0005,
    },
    {
        "header": {
            "sec-ch-ua": '"Chromium";v="124", "Microsoft Edge";v="124", "Not-A.Brand";v="99"',
            "sec-ch-ua-mobile": "?1",
            "sec-ch-ua-platform": '"Android"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Mobile Safari/537.36 EdgA/124.0.0.0",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br, zstd",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0004,
    },
    {
        "header": {
            "sec-ch-ua": '"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"Windows"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0004,
    },
    {
        "header": {
            "sec-ch-ua": '"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"Linux"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0004,
    },
    {
        "header": {
            "sec-ch-ua": '"Not_A Brand";v="8", "Chromium";v="120", "DuckDuckGo";v="120"',
            "sec-ch-ua-mobile": "?1",
            "sec-ch-ua-platform": '"Android"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br, zstd",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0004,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 17_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1.1 Mobile/15E148 Safari/604.1",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0004,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 15_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Mobile/15E148 Safari/604.1",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0004,
    },
    {
        "header": {
            "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
            "Accept-Language": "en-US;q=1.0",
            "Accept-Encoding": "gzip, deflate, br",
            "Upgrade-Insecure-Requests": "1",
            "Sec-Fetch-Dest": "navigate",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-User": "document",
            "Te": "trailers",
        },
        "probability": 0.0004,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0004,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 16_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko)  Mobile/15E148 Safari/604.1",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0004,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
            "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1 (compatible; woorankreview/2.0; +https://www.woorank.com/)",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0004,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 17_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) EdgiOS/124.0.2478.50 Version/17.0 Mobile/15E148 Safari/604.1",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
            "Sec-Fetch-Dest": "navigate",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-Site": "?1",
        },
        "probability": 0.0004,
    },
    {
        "header": {
            "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="96"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"Linux"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br, zstd",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0004,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0004,
    },
    {
        "header": {
            "sec-ch-ua": '"Google Chrome";v="113", "Chromium";v="113", "Not-A.Brand";v="24"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"Linux"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0004,
    },
    {
        "header": {
            "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
            "Accept-Language": "en-US;q=1.0",
            "Accept-Encoding": "gzip, deflate, br, zstd",
            "Upgrade-Insecure-Requests": "1",
            "Sec-Fetch-Dest": "navigate",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-User": "document",
            "Te": "trailers",
        },
        "probability": 0.0004,
    },
    {
        "header": {
            "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
            "Accept-Language": "en-US;q=1.0",
            "Accept-Encoding": "gzip, deflate, br, zstd",
            "Upgrade-Insecure-Requests": "1",
            "Sec-Fetch-Dest": "navigate",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-User": "document",
            "Te": "trailers",
        },
        "probability": 0.0004,
    },
    {
        "header": {
            "sec-ch-ua": '"Not:A-Brand";v="99", "Chromium";v="112"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"Linux"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0004,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 17_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/125.3  Mobile/15E148 Safari/605.1.15",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
            "Sec-Fetch-Dest": "navigate",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-Site": "?1",
        },
        "probability": 0.0004,
    },
    {
        "header": {
            "User-Agent": "Mozilla/5.0 (Android 13; Mobile; rv:125.0) Gecko/125.0 Firefox/125.0",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
            "Accept-Language": "en-US;q=1.0",
            "Accept-Encoding": "gzip, deflate, br",
            "Upgrade-Insecure-Requests": "1",
            "Sec-Fetch-Dest": "navigate",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-User": "document",
            "Te": "trailers",
        },
        "probability": 0.0004,
    },
    {
        "header": {
            "sec-ch-ua": '"Google Chrome";v="111", "Not(A:Brand";v="8", "Chromium";v="111"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"Windows"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0003,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0003,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0003,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 17_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko)  Mobile/15E148 Safari/604.1",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0003,
    },
    {
        "header": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 16_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Mobile/15E148 Safari/604.1",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0003,
    },
    {
        "header": {
            "sec-ch-ua": '"Chromium";v="118", "Google Chrome";v="118", "Not=A?Brand";v="99"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"Linux"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br, zstd",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0003,
    },
    {
        "header": {
            "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="96"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"Linux"',
            "Upgrade-Insecure-Requests": "1",
            "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Sec-Fetch-Site": "?1",
            "Sec-Fetch-Mode": "same-site",
            "Sec-Fetch-User": "document",
            "Sec-Fetch-Dest": "navigate",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US;q=1.0",
        },
        "probability": 0.0003,
    },
]
